### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by unclepaul84** [unclepaul84/allcountjs#1]
- [x] Create ADAL auth provider #2 
- [x] Regex Field Validation
- [x] JsonSchema based field type (http://jeremydorn.com/json-editor/,https://github.com/jdorn/json-editor) #3
- [x] Webhook calls on CRUD operations (https://github.com/roccomuso/node-webhooks)
- [ ] Support Custom Logo in header
- [ ] Support adding actions to user menu
- [ ] Support  Limiting columns and Filtering in Fields.relation
- [ ] Support rendering multiple views on homepage configured thru manifest
- [ ] Support google sheets export #6 
- [ ] Support arbitrary urils in Menu
- [ ] Support color label tag based on field value

**Comment by danmaxis** [comment]
Congrats on keeping this project
